name: E2E Tests on Chrome
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    name: E2E Tests on Chrome
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start
          browser: chrome
